/** Downloads the two open-licensed typefaces once and vendors them into
 * public/fonts/ so the running site never contacts a font CDN.
 * Only the latin subset is kept; both families are variable, so one file
 * per family covers every weight the design uses. */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "public/fonts");
await fs.mkdir(output, { recursive: true });

// Google serves woff2 only to browsers that advertise support.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const families = [
  {
    slug: "bodoni-moda",
    query: "Bodoni+Moda:opsz,wght@6..96,400..700",
    license:
      "https://raw.githubusercontent.com/google/fonts/main/ofl/bodonimoda/OFL.txt",
  },
  {
    slug: "archivo",
    query: "Archivo:wght@400..700",
    license:
      "https://raw.githubusercontent.com/google/fonts/main/ofl/archivo/OFL.txt",
  },
];

async function get(url, headers = {}) {
  const response = await fetch(url, { headers });
  if (!response.ok) throw new Error(url + ": " + response.status);
  return response;
}

const blocks = [];
for (const family of families) {
  const css = await (
    await get(
      "https://fonts.googleapis.com/css2?family=" +
        family.query +
        "&display=swap",
      { "User-Agent": UA },
    )
  ).text();
  // Keep the latin subset only: every glyph this interface renders is latin.
  const latin = [...css.matchAll(/@font-face\s*\{([^}]+)\}/g)]
    .map((m) => m[1])
    .find((b) => /unicode-range:[^;]*U\+0000-00FF/i.test(b));
  if (!latin) throw new Error("No latin subset returned for " + family.slug);
  const field = (name) =>
    latin.match(new RegExp(name + ":\\s*([^;]+);"))?.[1].trim();
  const url = latin.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) throw new Error("No woff2 returned for " + family.slug);
  const file = family.slug + ".woff2";
  await fs.writeFile(
    path.join(output, file),
    Buffer.from(await (await get(url)).arrayBuffer()),
  );
  blocks.push(
    "@font-face {\n" +
      "  font-family: " +
      field("font-family") +
      ";\n" +
      "  font-style: " +
      (field("font-style") ?? "normal") +
      ";\n" +
      "  font-weight: " +
      (field("font-weight") ?? "400") +
      ";\n" +
      "  font-display: swap;\n" +
      "  src: url(/fonts/" +
      file +
      ") format('woff2');\n" +
      "  unicode-range: " +
      field("unicode-range") +
      ";\n}",
  );
  await fs.writeFile(
    path.join(output, family.slug + "-OFL.txt"),
    Buffer.from(await (await get(family.license)).arrayBuffer()),
  );
  console.log("Vendored " + family.slug + ".woff2");
}

await fs.writeFile(
  path.join(output, "fonts.css"),
  "/* Generated by scripts/prepare-fonts.mjs. SIL Open Font License 1.1;\n" +
    "   the full licenses sit beside this file. Do not edit by hand. */\n" +
    blocks.join("\n") +
    "\n",
);
console.log("Wrote public/fonts/fonts.css");
